### ISSUE TITLE
Unable to change and save core settings

### ISSUE THREAD

**Issue by DrUm78** [libretro/fbalpha2012#112]
Hardware: FunKey S (SoC V3s ARM Cortex A7-A clocked @ 1.2GHz)
Software: sdlretro for the frontent (https://github.com/FunKey-Project/sdlretro) and FBAlpha 2012 for the Libretro core

I'm unable to save the core settings. As soon as I quit the menu and enter it again, the default settings are back and only partial setting are saved in "/.sdlretro/cfg/cores/fb_alpha_2012.json". Here is the content of my file:
```
{
    "": "Hold Start + A + B"
}
```
This bug also occurs with MAME 2000 core, but not in others as ScummVM or PrBoom for instance.

**Comment by Puxirepublic** [comment]
At first I thought it was caused by core itself, but after have tested from the RA core archives - counted by your post date: v1.9.5, descended to the v1.9.0, all old ones are facing the same issue as current one (nightly build: 9/10). So I'm sure the issue is caused by RA frontend. There's must be a conflict between frontend and this core; and also must be mentioned that all separate ones (cps1/2/3. neo-geo) don't have this issue, they all fine.

**Comment by DrUm78** [comment]
Seems it was due to my frontend, no more this issue with another one. Closed.
